disabled_rules:
- force_cast
- force_try
- identifier_name
- line_length
- shorthand_operator
- trailing_whitespace
- type_name
- function_parameter_count
- function_body_length
- nesting
- cyclomatic_complexity

file_length:
    warning: 1000
    error: 2000
    
opt_in_rules:
- mark
- todo

excluded:
- GEON-PPANG-iOS/Application

